stages:
- test

all_branch_test:
  stage: test
  tags:
  - docker
  image: python:3.9
  script:
  - apt-get update ##[edited]
  - apt-get install ffmpeg libsm6 libxext6 -y
  - pip install cython
  - pip install -r requirements-test.txt --no-cache-dir
  - pip install codecov
  - pytest --cov=rudalle_paddle tests/
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  except:
  - tags
